services:
  db:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 5
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
    user: postgres
    build:
      context: .
      dockerfile: dev_db/dockerfile_with_dummy_data
    volumes:
      - ./container_data/dev_db:/
  adminer:
    extends:
      file: common-services.yml
      service: adminer
